# Generated by Django 4.0.3 on 2022-04-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_hide_email_account_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='slug',
            field=models.SlugField(max_length=300, null=True, unique=True),
        ),
    ]
