# Generated by Django 4.0.3 on 2022-04-16 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_account_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountFollowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('fp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='x', to=settings.AUTH_USER_MODEL)),
                ('ps', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='y', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
