# Generated by Django 4.0.3 on 2022-04-17 00:25

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_rename_ps_accountfollowing_sp'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='cover_image',
            field=models.ImageField(blank=True, default=account.models.get_default_cover_image, max_length=255, null=True, upload_to=account.models.get_cover_image_filepath),
        ),
    ]
