# Generated by Django 4.0.3 on 2022-04-17 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_post_expire_date_post_is_expirable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_fav',
        ),
    ]
