# Generated by Django 4.0.3 on 2022-04-17 23:18

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_remove_post_post_fav'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('active_posts', django.db.models.manager.Manager()),
            ],
        ),
    ]
