# Generated by Django 4.0.3 on 2022-04-17 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_alter_post_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
            ],
        ),
    ]
