# Generated by Django 4.0.3 on 2022-04-20 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0016_room_tag_post_room_post_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_id',
            field=models.IntegerField(default=0),
        ),
    ]
