# Generated by Django 4.0.3 on 2022-04-20 00:40

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0018_alter_room_room_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover_image',
            field=models.ImageField(default=post.models.get_default_cover_image, max_length=255, upload_to=post.models.get_cover_image_filepath),
        ),
    ]
