# Generated by Django 4.0.4 on 2022-04-22 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0023_rename_image_room_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='verbose',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
