# Generated by Django 4.0.4 on 2022-04-25 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0027_alter_commentlike_comment_alter_commentlike_liker'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_cover_image_default',
            field=models.BooleanField(default=True),
        ),
    ]
