# Generated by Django 4.0.4 on 2022-04-25 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0028_post_is_cover_image_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
